name: Check



on: push



permissions:
  contents: read
  id-token: write



jobs:

  test-JSR:

    runs-on: ubuntu-24.04-arm
    timeout-minutes: 3
    strategy:
      matrix:
        deno:
          - ~2.4
          - ^2.5

    steps:

      - name: Setup repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup deno
        uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: |-
          CI=1 deno task test --coverage --coverage-raw-data-only --parallel --quiet
          deno coverage --include=src --lcov --output=coverage/cov.lcov
          deno coverage --include=src

      - name: Run codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          files: coverage/cov.lcov
          use_oidc: true



  test-npm:

    runs-on: ubuntu-24.04-arm
    timeout-minutes: 3

    steps:

      - name: Setup repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: v24

      - name: Move package.json
        run: cp tmp-package.json package.json

      - name: Install
        run: |-

          npm install --no-{fund,package-lock}
          npm install --no-{fund,package-lock,save} typescript@5.9.2 esbuild@0.25.9

      - name: Build
        run: npx tsc

      - name: Bundle
        run: npx esbuild  ./dist/utils.js
                --outfile=./dist/utils.js
                --format=esm
                --allow-overwrite
                --bundle

      - name: Replace
        run: |-

          find ./dist -type f -name '*.js'   -exec perl -i -pe 's/^var /const /g' {} \;
          find ./dist -type f -name '*.d.ts' -exec perl -i -pe "s/\.ts';/.js';/g" {} \;

      - name: Publish --dry-run
        run: npm publish --access=public --tag=next --dry-run
