name: Publish to JSR



on:
  push:
    tags:
      - v/*



jobs:

  publish-JSR:

    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      contents: read
      id-token: write

    steps:

      - name: Setup repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2

      - run: deno publish

