name: Publish to JSR



on:
  push:
    tags:
      - v/*



jobs:

  publish-JSR:

    runs-on: ubuntu-latest
    timeout-minutes: 3

    permissions:
      contents: read
      id-token: write

    steps:

      - name: Setup repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2

      - run: deno publish

